services:
  master:
    image: ros:noetic-ros-core
    command: roscore
    environment:
      DISPLAY: $DISPLAY
    network_mode: host
    restart: always
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority

  cam0:
    build: .
    depends_on:
      - master
    environment:
      DISPLAY: $DISPLAY
    command: roslaunch --wait camera.launch name:=cam0 video_device:=/dev/video1
    network_mode: host
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - ./launch/camera.launch:/root/catkin_ws/camera.launch

  remote_driving:
    build: .
    depends_on:
      - master
    environment:
      DISPLAY: $DISPLAY
      PYTHONUNBUFFERED: 1
    command: roslaunch --wait remote_driving.launch rate:=0.2
    network_mode: host
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - ./packages/remote_driving:/root/catkin_ws/src/remote_driving
      - ./launch/remote_driving.launch:/root/catkin_ws/remote_driving.launch