services:
  remote_driving:
    build: .
    environment:
      DISPLAY: $DISPLAY
      PYTHONUNBUFFERED: 1
      # Set ROS environment variables for the remote master
      ROS_MASTER_URI: ${ROS_MASTER_URI_SET}
      ROS_IP: ${ROS_IP_SET}
    command: roslaunch --wait remote_driving.launch rate:=0.2
    network_mode: host
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - ./packages/remote_driving:/root/catkin_ws/src/remote_driving
      - ./launch/remote_driving.launch:/root/catkin_ws/remote_driving.launch

  husky_teleop:
    build: .
    command: roslaunch husky_control teleop.launch
    network_mode: host
    environment:
      - DISPLAY=$DISPLAY
      - ROS_MASTER_URI=${ROS_MASTER_URI_SET}
      - ROS_IP=${ROS_IP_SET}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority